### ISSUE TITLE
[React] Signup and login forms

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#64]
## Context
We need signup and login forms on the React app

## Acceptance criteria
[ ] http://localhost:3000/login shows a login form with fields `username` and `password`
[ ] http://localhost:3000/signup shows a signup form with fields `username` and `password`
[ ] Submitting the form on http://localhost:3000/signup makes a POST request to the `http://127.0.0.1:8000/auth/users/` URL, and returns a JSON web token, and stores the username and password into local storage. If the user already exists, an error displays on the page.
[ ] Submitting the form on  http://localhost:3000/login submits a POST request to `http://127.0.0.1:8000/obtain_token` (the Django app), returns a JSON web token, and stores the username and password in local storage

NOTE: the best way to test this functionality is to have the Django app at github.com/codebuddies/django-concept running; otherwise, we can fake the API responses in our local JSON file in this repo.

**Comment by BethanyG** [comment]
Assigning myself to this as well.  Will be making a branch `issue-64-extended` to test "wiring up" these forms to the DRF backend.

**Comment by sebbel** [comment]
hey @BethanyG would you need help on this?

**Comment by BethanyG** [comment]
Apologies for the slow response!  

Yes - help to think through this would be great.  Since we're starting to have discussions around possibly adding social auth, this might now be less straightforward than simply "hooking up" the backend....although hooking up the backend as-is would also be a great first step.   

The backend **asks** (a POST with new user info)/**checks** (a POST with existing user info) for a username and password stored in the DB , and will issue a JWT token if it finds correct information.  That JWT token is then expected for subsequent requests to any endpoint we wrap in "auth required". 

But if we want to use **`social auth`**, we'll need to modify things backend (and/or frontend) to include making the social authorization request and storing additional/different information (tokens, expiration, etc.) depending on the outside authorization source BEFORE we then issue a JWT token.

That changes the login and signup flow front-end, I would imagine - and it would certainly change the creation and auth flows backend.

I haven't dug in more than that because my Resources serializer bug is still pending and taking all of my time, sadly.

Here's some links for social auth/DRF for the backend:

**Python-social-auth:** https://python-social-auth.readthedocs.io/en/latest/
**Django Social Auth with Django Rest:** https://medium.com/esketchers/django-social-auth-integration-with-django-rest-framework-9c04469e378f
**(Older) Social Auth with Django REST:** https://yeti.co/blog/social-auth-with-django-rest-framework/

The first is a drop-in library that looks to be the "default" for Django social auth, although I suspect there are more out there.  It allows for different services to be plugged in, and provides the different models necessary to persist user data in the DB.  The other two are implementation articles, and not necessarily what we'd do - but are a place to start.

**Comment by lpatmo** [comment]
Thank you for the detailed notes! 

From a product perspective, probably the most important social auth to support is GitHub; I don't think we need to prioritize others, tbh. :) Can file that issue when this particular flow (signup with username/password) is implemented. 

Unrelated: some folks were interested in magic links -- I can start a separate issue thread to discuss that too!
